### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by SuperErnD** [Sitiaro/Discord.py#3]
### Help!
eng:
I tried to port the level system to my bot, but it does not respond, I write rank and nothing to do the database is in place
rus: 
Я пытался портировать в своего бота систему уровней но она не отвечает пишу rank и ничего что делать база данных на месте

**Comment by Sitiaro** [comment]
Check the comments in levels.py file and makes changes to it accordingly. You'll have to create a mongodb account and do certain things for it to work.

Проверьте комментарии в файле level.py и внесите в него соответствующие изменения. Вам нужно будет создать учетную запись mongodb и выполнить определенные действия, чтобы она заработала.

**Comment by SuperErnD** [comment]
> Проверьте комментарии в файле level.py и внесите в него соответствующие изменения. Вам нужно будет создать учетную запись mongodb и выполнить определенные действия, чтобы она заработала.
> 
> Используйте комментарии в файле level.py и внесите в него временные изменения. Вам необходимо создать учетную запись mongodb и установление закона, чтобы она заработала.

я вроде же так сделал
I kinda did it

**Comment by Sitiaro** [comment]
Добавь меня discord:
 𝚇𝚒𝚗 心 ❧#8888

**Comment by SuperErnD** [comment]
> 𝚇𝚒𝚗 心 ❧#8888

okay , im TheDiman#2022
